# Generated by Django 3.1 on 2025-06-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='Image',
        ),
    ]
