# Generated by Django 3.1 on 2025-06-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20250619_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='Image',
            new_name='image',
        ),
    ]
